name: augmento
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+8

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  get: ^4.7.2
  get_storage: ^2.1.1
  fluttertoast: ^9.0.0
  connectivity_plus: ^7.0.0
  google_fonts: ^6.3.1
  font_awesome_flutter: ^10.10.0
  intl: ^0.20.2
  file_picker: ^10.3.3
  flutter_keyboard_visibility: ^6.0.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  new_version_plus: ^0.1.1
  flutter_offline: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/applogo.png

flutter_launcher_icons:
  image_path: assets/applogo.png
  android: true
  ios: true